[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pychronicle"
version = "1.0.0source venv"
description = "A Python runtime execution tracer and time-travel debugging tool."
readme = { file = "README.md", content-type = "text/markdown" }
dependencies = [
    "textual>=0.82.8",
    "typer>=0.12.5"
]

[project.scripts]
pychronicle = "pychronicle.__main__:app"
